_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "checkpoints/coco/cocobase.pth"
  MASK_ON: False
  BACKBONE:
    FREEZE: False
    WITHSCSM: True

  RESNETS:
    DEPTH: 101
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: True
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NUM_CLASSES: 20
    FREEZE_FEAT: True
    CLS_DROPOUT: True
DATASETS:
  TRAIN: ('coco14_trainval_novel_30shot_seed0',)
  TEST: ('coco14_test_novel',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (900, 1200)
  MAX_ITER: 14000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 20
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 1000

OUTPUT_DIR: "checkpoints/FGSM_ablation/coco_randomerase_feature/30shot" 