_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  BACKBONE:
    WITHSCSM: True
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
  ROI_HEADS:
    NUM_CLASSES: 15
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.75
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ('voc_2007_trainval_base2', 'voc_2012_trainval_base2')
  TEST: ('voc_2007_test_base2',)
SOLVER:
  STEPS: (10000, 20000)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
  WARMUP_ITERS: 100

  IMS_PER_BATCH: 10
  BASE_LR: 0.01

TEST:
  EVAL_PERIOD: 5000
