_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/home/xzm/xzm/FOOD/scsm/output/modelsurg/coco/scsm/model_reset_surgery.pth"
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_swin_backbone"
    FREEZE: True
    # NAME: "build_resnet_backbone"
    WITHSCSM: True
    FREEZESCSM: False
  SWIN:
      EMBED_DIM: 192
      DROP_PATH_RATE: 0.3
      NUM_HEADS: [6,12,24,48]
      DEPTHS: [2,2,18,2]
      IMG_SIZE: 384
      SQUARE_PAD: 1024
      WINDOW_SIZE: 12
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
    IN_FEATURES: ["p3"]
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.01
    NUM_CLASSES: 80
    FREEZE_FEAT: False
    CLS_DROPOUT: True
    IN_FEATURES: ["p3"]
# INPUT:
#   MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
#   MIN_SIZE_TEST: 800
# DATASETS:
#   TRAIN: ('coco14_trainval_all_10shot_seed0',)
#   TEST: ('coco14_test_all',)
DATASETS:
  TRAIN: ('coco14_trainval_all_10shot_seed0',)
  TEST: ('coco14_test_all',)

SOLVER:
  TYPE: "AdamW"
  BASE_LR: 0.001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  BIAS_LR_FACTOR: 1.0
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 12
  # BASE_LR: 0.005
  STEPS: (2500, 6500)
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 20
TEST:
  PCB_ENABLE: True
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
  EVAL_PERIOD: 1001
OUTPUT_DIR: "/home/xzm/xzm/FOOD/scsm/output/swin-l/coco/scsm/30shot" 