_BASE_: "../Base-RCNN.yaml"
MODEL:
  WEIGHTS: "/home/xzm/xzm/FOOD/scsm/output/modelsurg/voc/sfa/base1/model_reset_surgery.pth"
  META_ARCHITECTURE: "GeneralizedRCNN"
  MASK_ON: False
  BACKBONE:
    NAME: "build_swin_backbone"
    FREEZE: True
    # NAME: "build_resnet_backbone"
    WITHSFA: True
    FREEZE_SFA: True
  SWIN:
      EMBED_DIM: 192
      DROP_PATH_RATE: 0.3
      NUM_HEADS: [6,12,24,48]
      DEPTHS: [2,2,18,2]
      IMG_SIZE: 384
      SQUARE_PAD: 1024
      WINDOW_SIZE: 12
  RPN:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.0
    FREEZE: False
    IN_FEATURES: ["p3"]
  ROI_HEADS:
    ENABLE_DECOUPLE: True
    BACKWARD_SCALE: 0.001
    NUM_CLASSES: 20
    FREEZE_FEAT: False
    CLS_DROPOUT: True
    IN_FEATURES: ["p3"]
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 800
DATASETS:
  TRAIN: ("voc_2007_trainval_all1_1shot_seed1", )
  TEST: ("voc_2007_test_all1",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (200, 600)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 500
  WARMUP_ITERS: 0
TEST:
  EVAL_PERIOD: 501
  PCB_MODELPATH: "ImageNetPretrained/torchvision/resnet101-5d3b4d8f.pth"
