from detectron2.config.defaults import _C
from detectron2.config import CfgNode as CN

_CC = _C

# ----------- Backbone ----------- #
_CC.MODEL.BACKBONE.FREEZE = False
_CC.MODEL.BACKBONE.FREEZE_AT = 3
_CC.MODEL.BACKBONE.WITHECEA = False
_CC.MODEL.BACKBONE.FREEZE_ECEA = False
_CC.MODEL.BACKBONE.WITHMAMBA = False
_CC.MODEL.BACKBONE.WITHSCSM = False
_CC.MODEL.BACKBONE.WITHSFASA = False
_CC.MODEL.BACKBONE.WITHSFASENet = False
_CC.MODEL.BACKBONE.CNN = False
_CC.MODEL.BACKBONE.ATTACK = False


_CC.MODEL.BACKBONE.DATA_AUG_TYPE = "None"  # "Cutout", "Mixup", "CutMix", "None
_CC.MODEL.BACKBONE.FEATURE_AUG_TYPE = "None"  # "Cutout", "Mixup", "CutMix", "None

#_CC.MODEL.SWIN.OUT_INDICES = [3]

# ------------- RPN -------------- #
_CC.MODEL.RPN.FREEZE = False
_CC.MODEL.RPN.ENABLE_DECOUPLE = False
_CC.MODEL.RPN.BACKWARD_SCALE = 1.0

# ------------- ROI -------------- #
_CC.MODEL.ROI_HEADS.NAME = "Res5ROIHeads"
_CC.MODEL.ROI_HEADS.FREEZE_FEAT = False
_CC.MODEL.ROI_HEADS.ENABLE_DECOUPLE = False
_CC.MODEL.ROI_HEADS.BACKWARD_SCALE = 1.0
_CC.MODEL.ROI_HEADS.OUTPUT_LAYER = "FastRCNNOutputLayers"
_CC.MODEL.ROI_HEADS.CLS_DROPOUT = False
_CC.MODEL.ROI_HEADS.DROPOUT_RATIO = 0.8
_CC.MODEL.ROI_BOX_HEAD.POOLER_RESOLUTION = 7  # for faster

# ------------- TEST ------------- #
_CC.TEST.PCB_ENABLE = False
_CC.TEST.PCB_MODELTYPE = 'resnet'             # res-like
_CC.TEST.PCB_MODELPATH = ""
_CC.TEST.PCB_ALPHA = 0.50
_CC.TEST.PCB_UPPER = 1.0
_CC.TEST.PCB_LOWER = 0.05

# ------------ Other ------------- #
_CC.SOLVER.WEIGHT_DECAY = 5e-5
_CC.MUTE_HEADER = True
_CC.SAVE_VIS_PLT = False
_CC.SAVE_ROI_FEATURE = False
_CC.SAVE_ATTENTION_MAP = False

#_CC.SEED = 43

_CC.SOLVER.TYPE = "SGD"